version: "3"

tasks:
  help:
    desc: print this help message
    cmds:
      - task --list-all
    silent: true

  confirm:
    desc: confirmation prompt
    cmds:
      - |
        echo -n 'Are you sure? [y/N] ' && read ans && [ ${ans:-N} = y ]
    silent: true
    internal: true

  run:
    desc: run the cmd/go-boilerplate application
    cmds:
      - go run ./cmd/go-boilerplate

  compose:up:
    desc: start local database and redis
    cmds:
      - docker compose up -d

  compose:down:
    desc: stop local database and redis (keeps volumes)
    cmds:
      - docker compose down

  compose:down-v:
    desc: stop local database and redis and delete volumes
    cmds:
      - docker compose down -v

  test:
    desc: run all tests
    cmds:
      # only for users using colima for docker runtime instead of docker desktop in macos, else comment, the next two lines
      - export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"
      - export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
      - go test ./...

  migrations:new:
    desc: create a new database migration
    vars:
      NAME: '{{.name | default ""}}'
    cmds:
      - |
        if [ -z "{{.NAME}}" ]; then
          echo "Error: name parameter is required"
          echo "Usage: task migrations:new name=migration_name"
          exit 1
        fi
      - echo 'Creating migration file for {{.NAME}}...'
      - tern new -m ./internal/database/migrations {{.NAME}}

  migrations:up:
    desc: apply all up database migrations
    deps: [confirm]
    dotenv:
      - .env
    cmds:
      - echo 'Running up migrations...'
      - tern migrate -m ./internal/database/migrations --conn-string "$BOILERPLATE_DB_DSN"

  tidy:
    desc: format all .go files, and tidy and vendor module dependencies
    cmds:
      - echo 'Formatting .go files...'
      - go fmt ./...
      - echo 'Tidying module dependencies...'
      - go mod tidy
      - echo 'Verifying dependencies...'
      - go mod verify
